name: "GPG key import"
description: "Import private GPG key. Patched version of hashicorp/ghaction-import-gpg"
runs:
  using: "composite"
  steps:
    - run: |
        #
        echo -e "${{ env.GPG_PRIVATE_KEY }}" | gpg --import --batch --no-tty
        echo "hello world" > temp.txt
        gpg --detach-sig --yes -v --output=/dev/null --pinentry-mode loopback --passphrase "${{ env.PASSPHRASE }}" temp.txt
        rm temp.txt
      shell: bash
      name: import GPG key and prime passphrase
    - id: gpg-fingerprint
      run: |
        fingerprint=$(gpg --with-colons --list-keys | awk -F: '/^pub/ { print $5 }')
        echo "::set-output name=fingerprint::$fingerprint"
      shell: bash
      name: set gpg fingerprint output

outputs:
  fingerprint:
    description: "Fingerprint of the GPG key (recommended as user ID)"
    value: ${{ steps.gpg-fingerprint.outputs.fingerprint }}