name: Auto-Merge Dependabot

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  auto-merge:
    name: '🤖 Auto-Merge Dependabot'
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:

      - name: Harden Runner
        uses: step-security/harden-runner@6c439dc8bdf85cadbbce9ed30d1c7b959517bc49 # v2.12.2
        with:
          egress-policy: audit

      - name: Check Out
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          
      - uses: ahmadnassri/action-dependabot-auto-merge@45fc124d949b19b6b8bf6645b6c9d55f4f9ac61a # v2.6.6
        with:
          target: minor
          github-token: ${{ secrets.DEPENDABOT_PAT }}