name: Close Stale Issues

on:
  schedule:
    - cron: '0 8 * * *'  # Run daily at 8 AM UTC
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@6c439dc8bdf85cadbbce9ed30d1c7b959517bc49 # v2.12.2
        with:
          egress-policy: audit

      - uses: actions/stale@5bef64f19d7facfb25b37b414482c7164d639639 # v9.1.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          
          # Issue settings
          stale-issue-message: |
            This issue has been automatically marked as stale because it has not had recent activity. 
            It will be closed in 2 days if no further activity occurs. 
            If you believe this issue is still relevant, please comment to keep it open.
          close-issue-message: |
            This issue has been automatically closed due to inactivity. 
            If you believe this was closed in error, please reopen it or create a new issue.
          
          # PR settings  
          stale-pr-message: |
            This pull request has been automatically marked as stale because it has not had recent activity.
            It will be closed in 2 days if no further activity occurs.
          close-pr-message: |
            This pull request has been automatically closed due to inactivity.
            If you'd like to continue this work, please reopen it or create a new pull request.
          
          # Timing (in days)
          days-before-stale: 7
          days-before-close: 2
          
          # Labels
          stale-issue-label: 'stale'
          stale-pr-label: 'stale'
          exempt-issue-labels: 'pinned,security,bug,enhancement'
          exempt-pr-labels: 'pinned,security'
          
          # Behavior
          remove-stale-when-updated: true
          operations-per-run: 100