name: Generate Docs

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**/*'
      - 'scripts/**/*'
      - './.golangci.yml'
  workflow_dispatch:

permissions:
  contents: write  # Required to update documentation in the repo
  pull-requests: write

jobs:
  provider-docs:
    name: '📚 Generate Go and TF Provider Docs'
    runs-on: ubuntu-latest  # Standard runner for documentation generation
    steps:

    - name: Harden Runner
      uses: step-security/harden-runner@6c439dc8bdf85cadbbce9ed30d1c7b959517bc49 # v2.12.2
      with:
        egress-policy: audit
        
    - name: Check Out
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        
    - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
      with:
        cache: true
        cache-dependency-path: 'go.sum'
        go-version-file: 'go.mod'

    - uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # 3.1.2
      with:
        terraform_version: '1.12.1'
        terraform_wrapper: true
    
    # Creates provider documentation for godoc.org and pkg.go.dev
    - name: 'go generate'
      run: go generate ./...
    
    # Format all Terraform files
    - name: Format Terraform files
      run: |
        find . -type f -name "*.tf" -exec terraform fmt {} \;
    
    # Creates provider documentation for Terraform
    - name: Generate tf docs
      run: |
        go install github.com/hashicorp/terraform-plugin-docs/cmd/tfplugindocs
        cd $GITHUB_WORKSPACE
        tfplugindocs generate --provider-name terraform-provider-meraki --rendered-provider-name "Meraki"

    - name: Check for changes in generated Go docs and formatted Terraform files
      id: go-gen-check
      run: |
        if [[ -n $(git status --porcelain) ]]; then
          echo "changes=true" >> $GITHUB_OUTPUT
        else
          echo "changes=false" >> $GITHUB_OUTPUT
        fi

    - name: Create Pull Request with documentation updates
      if: steps.go-gen-check.outputs.changes == 'true'
      uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7.0.8
      with:
        commit-message: "chore: update go documentation, provider documentation and format terraform files"
        title: "📚 Auto-update documentation and format Terraform files"
        body: "Automated documentation update and Terraform file formatting."
        branch: docs/auto-update-${{ github.run_number }}
        delete-branch: true