name: Terraform Provider Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      release_version:
        description: 'TF Provider Release version to publish. Requires an pre-existing repo release and the provided value must be formatted as a semver.'
        required: true
        default: 'v0.0.0-alpha'


permissions:
  contents: write
  id-token: write
  packages: read
  statuses: write

jobs:
  pre-release-checks:
    name: '🚦 Pre-release Validation'
    runs-on: ubuntu-latest
    timeout-minutes: 30  # Reduced timeout for pre-release validation
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@6c439dc8bdf85cadbbce9ed30d1c7b959517bc49 # v2.12.2
      with:
        egress-policy: audit

    - name: Check out code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        fetch-depth: 0
        ref: ${{ github.event.inputs.release_version || github.ref }}

    - name: Set up Go
      uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
      with:
        cache: true
        cache-dependency-path: 'go.sum'
        go-version-file: 'go.mod'
      env:
        GOOS: linux
        GOARCH: arm64
      id: go

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3.1.2
      with:
        terraform_version: '1.10.2'
        terraform_wrapper: false

    - name: Run 'go mod tidy' and check for differences
      run: |
        go mod tidy
        git diff --exit-code -- go.mod go.sum || \
        (echo; echo "Unexpected difference in go.mod/go.sum files. Run 'go mod tidy' command or revert any go.mod/go.sum changes and commit."; exit 1)

    - name: Get go mod dependencies
      run: |
        go mod download

    - name: Go build
      run: |
        go build -v .
      env:
        CGO_ENABLED: 0
        GOMAXPROCS: 4

  # Release for Partner and Community Providers
  # https://goreleaser.com/cmd/goreleaser_release/#see-also
  terraform-provider-release:
    name: '📦 Terraform Provider Release'
    needs: [pre-release-checks]
    uses:  ./.github/workflows/tf-registry-goreleaser.yml
    secrets:
      gpg-private-key: '${{ secrets.GPG_PRIVATE_KEY }}'  # Your GPG private key
      gpg-private-key-passphrase: '${{ secrets.GPG_PRIVATE_KEY_PASSPHRASE }}'  # Passphrase for your GPG key, if applicable
    with:
      goreleaser-release-args: --verbose --timeout 60m # Parallelism set in workflow to avoid conflicts
      release-notes: false
      setup-go-version: '1.22.5'
      git-ref: ${{ github.event.inputs.release_version || github.ref }}

  release-notes:
    runs-on: ubuntu-latest
    needs: [terraform-provider-release]
    steps:

      - name: Harden Runner
        uses: step-security/harden-runner@6c439dc8bdf85cadbbce9ed30d1c7b959517bc49 # v2.12.2
        with:
          egress-policy: audit
          
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
      - name: Generate Release Notes
        run: sed -n -e "1{/# /d;}" -e "2{/^$/d;}" -e "/# $(git describe --abbrev=0 --exclude="$(git describe --abbrev=0 --match='v*.*.*' --tags)" --match='v*.*.*' --tags | tr -d v)/q;p" CHANGELOG.md > release-notes.txt
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: release-notes
          path: release-notes.txt
          retention-days: 1
